# -*- coding: utf-8 -*-
"""opencv_plant_foregrounder

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JdL1QxW8xf-2nxjnXPLLy57FQlMhV0k1


usage

in R you will make a system call/system command that says soemthign like "python opencv_plant_foregrounder.py -fname-" 
"""

import numpy as np
from sklearn.mixture import GaussianMixture as GMM
from PIL import Image
from pathlib import Path
import argparse
import os

parser = argparse.ArgumentParser("perform image segmentation with python")
parser.add_argument("fname")

args = parser.parse_args()
pth = Path(args.fname)
actual_image = Image.open(pth.absolute())
img = np.array(actual_image)
img2 = img.reshape((-1,3))

img2.shape

gmm_model = GMM(n_components=2,covariance_type="tied").fit(img2)

gmm_labels= gmm_model.predict(img2)

segmented = gmm_labels.reshape(img.shape[:2])
mod = img.copy()
group_val = segmented[0,0]
mod[segmented == group_val]=0

output = Image.fromarray((mod).astype("uint8"))

date = Path(f"{pth.parents[1]}/Segmented")
date.mkdir(exist_ok=True,parents=True)
output.save(f"{date.absolute()}/{pth.stem}_segmented.jpg")
print(f"finished {pth.stem}_segmented.jpg")
